AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "Please enter a valid e-mail adress")]
        public string Email { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }


    }
}

AarhusWebDevCoop/ViewModels/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class Message
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Message")]
        public string Msg { get; set; }

    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using Umbraco.Web.Mvc;
using System.Net.Mail;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurfaceController
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm form)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            MailMessage message = new MailMessage();
            message.To.Add("mymail@gmail.com");
            message.Subject = form.Subject;
            message.From = new MailAddress(form.Email, form.Name);
            message.Body = form.Message + "\n my email is: " + form.Email;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new NetworkCredential("mymail@gmail.com", "mypassword");
                smtp.EnableSsl = true;

                smtp.Send(message);
            }

            TempData["success"] = true;

            IContent comment = Services.ContentService.CreateContent(form.Subject, CurrentPage.Id, "Comment");

            comment.SetValue("commentName", form.Name);
            comment.SetValue("subject", form.Subject);
            comment.SetValue("email", form.Email);
            comment.SetValue("message", form.Message);

            //Save
            Services.ContentService.Save(comment);


            //Save & publish
            //Services.ContentService.SaveAndPublishWithStatus(comment);

            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Controllers/MessageBoardFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using umbraco.cms.businesslogic.member;

namespace AarhusWebDevCoop.Controllers
{
    public class MessageBoardFormSurfaceController : SurfaceController
    {
        // GET: MessageBoardFormSurface
        public ActionResult Index()
        {

            string loggedInUsername = Members.GetCurrentMember().Name;
            return PartialView("MessageBoardForm", new Message { Name = loggedInUsername });

        }

        [HttpPost]
        public ActionResult HandleSubmit(Message model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            IContent message = Services.ContentService.CreateContent(model.Name, CurrentPage.Id, "Message");
            message.SetValue("messageName", model.Name);
            message.SetValue("messageBody", model.Msg);

            Services.ContentService.SaveAndPublishWithStatus(message);

            return RedirectToCurrentUmbracoPage();
        }


    }
}

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="jumbotron">
<h1>@Umbraco.Field("articleTitle")</h1>
	@Umbraco.Field("articleContent")
	</div>

AarhusWebDevCoop/Views/ArticleMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticleMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@Umbraco.Field("mainContent")
@Umbraco.RenderMacro("ArticleItems")

AarhusWebDevCoop/Views/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm

@{
    Layout = null;
}


@if (TempData["success"] == null)
{



    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {

        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>

    }
}
else
{
    <p>Thank you for contacting us. We'll be in touch soon</p>
}

AarhusWebDevCoop/Views/ContactUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}


<h1>@CurrentPage.Name</h1>

@Html.Action("Index", "ContactFormSurface")

AarhusWebDevCoop/Views/GridAbout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Grid>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@CurrentPage.GetGridHtml("gridLayout")

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}


@if (!Members.GetCurrentLoginStatus().IsLoggedIn)
{
    Html.RenderPartial("Login");
}
else
{
    Html.RenderPartial("Logout");
}

AarhusWebDevCoop/Views/MacroPartials/Article Items.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").Reverse(); }

@if (selection.Any())
{

    foreach (var item in selection)
    {
        <div class="well">
            <h2><a href="@item.Url">@item.Name</a></h2>

            <p>
                @Umbraco.Truncate(item.articleContent.ToString(), 600)
            </p>
            <a href="@item.Url">See full article</a>

        </div>
    }

}

AarhusWebDevCoop/Views/MacroPartials/Main Navigation.cshtml
@using Umbraco.Web.Security
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@*
    This snippet displays a list of links of the pages immediately under the top-most page in the content tree.
    This is the home page for a standard website.
    It also highlights the current active page/section in the navigation with the css class "current".
*@
@{
    var selection = CurrentPage.Site().Children.Where("Visible");
    var umbracoHelper = new Umbraco.Web.UmbracoHelper();
   
}
<ul class="nav navbar-nav">
    <li>
        <a href="/">Home</a>
    </li>
    @foreach (var item in selection)
    {
        //Hide stuff you the logged in user dosen't have access to.
        
        var isProtected = library.IsProtected(item.id, item.path);
        var loginAccess = isProtected && library.HasAccess(item.id, item.path);


        if (!isProtected || loginAccess)
        {
            <li class="@(item.IsAncestorOrSelf(CurrentPage) ? "active" : null)">

                @if (item.DocumentTypeAlias == "projectMain")
                {
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@item.Name <span class="caret"></span></a>
                    @Umbraco.RenderMacro("ProjectDropdown")
                }

                else if (item.id == 4100 && umbraco.library.IsLoggedOn())
                {
                    <a href="@item.Url">Logout</a>
                }

                else
                {
                    <a href="@item.Url">@item.Name</a>
                }
            </li>
        }
    }
</ul>

AarhusWebDevCoop/Views/MacroPartials/Member List.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{
    var memberService = ApplicationContext.Current.Services.MemberService;

    var active = memberService.GetMembersByGroup("Active");
    var prospects = memberService.GetMembersByGroup("Prospect");
}

<div class="panel panel-default">
    <div class="panel-heading">Active Members</div>
    <div class="panel-body">

        @foreach (var member in active)
        {

            <div class="pull-left member">

                @{
                    //Photo stuff
                    string fullPath = member.GetValue("photo").ToString();
                    string[] substrings = fullPath.Split(',');
                    string srcString = substrings[2];
                    string[] srcSubStrings = srcString.Split(':');
                    string srcPath = srcSubStrings[1].Replace("\"", "");
                    srcPath = srcPath.Replace("}", "");

                    <img class="img-responsive memberPic" src="@srcPath" />
                    <p>

                        @(member.GetValue("firstname") + " " + member.GetValue("lastname")) <br />
                        @member.GetValue("address") <br />
                        @(member.GetValue("zip") + " " + @member.GetValue("city")) <br />
                        Mobile: @member.GetValue("mobile") <br />


                    </p>
                }
            </div>
                    }
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">Prospects</div>
    <div class="panel-body">
        @foreach (var member in prospects)
        {    <div class="pull-left member">
            <p>
                @(member.GetValue("firstname") + " " + member.GetValue("lastname")) <br />
                Mobile: @member.GetValue("mobile") <br />
            </p>
            
        </div>
        }
    </div>
</div>

AarhusWebDevCoop/Views/MacroPartials/Newest Projects.cshtml
@{
    var numOfProjects = Model.MacroParameters["NumOfProjects"];
    var selection = CurrentPage.Site().FirstChild("projectMain").Children.Where("status.Contains(\"Completed\")").OrderBy("CreateDate desc").Take(Convert.ToInt32(numOfProjects));

}
<ul>
	@foreach(var item in selection){
		<li>
			@item.Name
		</li>
	}
</ul>

@inherits Umbraco.Web.Macros.PartialViewMacroPage

AarhusWebDevCoop/Views/MacroPartials/NewestArticle.cshtml
@{
    var article = CurrentPage.Site().FirstChild("articleMain").Children.OrderBy("CreateDate desc").Take(1).First();

}


	
	<div class="well">
		<h3>@article.Name</h3>@article.articleContent</div>


@inherits Umbraco.Web.Macros.PartialViewMacroPage

AarhusWebDevCoop/Views/MacroPartials/Project Dropdown.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var selection = CurrentPage.Site().FirstChild("projectMain").Children.OrderBy("CreateDate desc");
}
<ul class="dropdown-menu">

    <li><a href="/projects">All Projects</a></li>
    <li class="divider"></li>

    @foreach (var item in selection)
    {
        if (item.status.ToString() != "Completed")
        {
            continue;
        }
        <li>
            <a href="@item.Url">@item.Name</a>
        </li>
    }
</ul>

AarhusWebDevCoop/Views/MacroPartials/Project Items.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible"); }

@if (selection.Any())
{
    <ul>
        @foreach (var item in selection)
        {
            <li>
                <h3><a href="@item.Url">@item.Name (@item.status)</a></h3>
            </li>
        }
    </ul>
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

<html>
<head>
    <title>@Umbraco.Field("pageTitle", altFieldAlias: "pageName")</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Logo</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    @Umbraco.RenderMacro("MainNavigation")
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/umbraco"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">

            <div class="col-sm-12 text-left">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="container-fluid text-center">
        <p>
            @Umbraco.Field("footer", recursive: true)
        </p>
    </footer>

    <script src="~/scripts/jquery-1.9.1.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>

    <script src="~/scripts/jquery.validate.min.js"></script>
    <script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
@Umbraco.RenderMacro("MemberList")

AarhusWebDevCoop/Views/MessageBoard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MessageBoard>
@using System.Security.Policy
@using ContentModels = Umbraco.Web.PublishedContentModels;



@{
    Layout = "Master.cshtml";
    var umbracoHelper = new Umbraco.Web.UmbracoHelper(Umbraco.UmbracoContext);
    

}
<h1>@CurrentPage.Name</h1>



@if (umbracoHelper.MemberIsLoggedOn())
{
    @Html.Action("Index", "MessageBoardFormSurface")
}


@{
    var selection = CurrentPage.Site().FirstChild("messageBoard").Children.Where("Visible").OrderBy("CreateDate desc");
}
@foreach (var item in selection)
{
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3> @item.messageName</h3><small>@umbraco.library.LongDate(@item.UpdateDate.ToString(), true, " - ")</small>
            <div class="panel-body">
                @item.messageBody
            </div>
        </div>
    </div>

}

AarhusWebDevCoop/Views/MessageBoardForm.cshtml
@using System.Activities.Statements
@using Umbraco;

@model AarhusWebDevCoop.ViewModels.Message

@{
    Layout = null;
 
}




@using (Html.BeginUmbracoForm("HandleSubmit", "MessageBoardFormSurface", new object { }, new { @class = "form-horizontal" }))
{

    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
            @Html.ValidationMessageFor(m => m.Name)
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.Msg, new { @class = "col-sm-2 control-label" })
        <div class="col-sm-6">
            @Html.TextAreaFor(m => m.Msg, new { @class = "form-control", placeholder = "Your message" })
            @Html.ValidationMessageFor(m => m.Msg)
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
        </div>
    </div>

}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AarhusWebDevCoop/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    var UmbracoHelper = new UmbracoHelper(UmbracoContext.Current);
    
    markup = markup.Replace("#value#", UmbracoHelper.ReplaceLineBreaksForHtml(Model.value.ToString()));
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

AarhusWebDevCoop/Views/Partials/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel {RedirectUrl = "/"};

    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()


<h1>@Umbraco.Field("pageTitle")</h1>

    @using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
    {
        @Html.ValidationSummary("loginModel", true)
        <div class="form-group">
            @Html.LabelFor(m => loginModel.Username)
            @Html.TextBoxFor(m => loginModel.Username)
            @Html.ValidationMessageFor(m => loginModel.Username)

        </div>
        <div class="form-group">
            @Html.LabelFor(m => loginModel.Password)
            @Html.PasswordFor(m => loginModel.Password)
            @Html.ValidationMessageFor(m => loginModel.Password)
        </div>


        <button type="submit" class="btn btn-default">Login</button>
    }

AarhusWebDevCoop/Views/ProjectItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ProjectItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}
<h1>@Umbraco.Field("projectTitle")</h1>
<label>Status: </label>
<p>@Umbraco.Field("status")</p>


<div class="well">

    @Umbraco.Field("description")
</div>